// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"
)

type Account struct {
	ID   int64
	Uid  string
	Name string
	Bio  sql.NullString
}

type Category struct {
	ID        int64
	AccountID int64
	Content   sql.NullString
}

type Tweet struct {
	ID        int64
	AccountID int64
	Content   sql.NullString
}
