services:
  db:
    image: mysql:8.0
    container_name: tweet_driven_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_TCP_PORT: 3309
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3309:3309
  go:
    image: go_image
    build: .
    environment:
      DB_ADDR: tweet_driven_db
    restart: always


volumes:
  db-store:
