SET FOREIGN_KEY_CHECKS = 0;
truncate categories;
truncate accounts;
truncate tweets;
truncate tweets_categories;
drop table accounts;
drop table tweets;
drop table categories;
drop table tweets_categories;
SET FOREIGN_KEY_CHECKS = 1;
